In [1]:
# 
# Retrieve fund quarterly reports over period of time
#

In [2]:
#
# Install forms13f python sdk 
#
try:
    import forms13f 
    print('forms13f forms13f package is already installed')
except ImportError:
    # Package not found, so install it from GitHub
    !pip install git+https://github.com/forms13f/python-sdk.git

forms13f forms13f package is already installed

In [3]:
#
# Get aggregated quarter report from form 13F and subsequent amendments
#
from pprint import pprint
import report
# Example usage
quarter = "2023-Q3"
cik = "0001067983"  # Example CIK for Berkshire Hathaway Inc
quarter_report = report.QuarterReport(quarter, cik)
quarter_report.display_header_as_html()
quarter_report.display_holdings(output='as_html')

,Name,Symbol,CUSIP,"Value, $k",Shares,%
4,APPLE INC,AAPL,037833100,"156,753,093","915,560,382",49.77
6,BANK AMER CORP,BAC,060505104,"28,279,487","1,032,852,006",8.98
2,AMERICAN EXPRESS CO,AXP,025816109,"22,618,800","151,610,700",7.18
12,COCA COLA CO,KO,191216100,"22,392,000","400,000,000",7.11
9,CHEVRON CORP NEW,CVX,166764100,"18,590,066","110,248,289",5.90
36,OCCIDENTAL PETE CORP,OXY,674599105,"14,541,501","224,129,192",4.62
20,KRAFT HEINZ CO,KHC,500754106,"10,954,355","325,634,818",3.48
33,MOODYS CORP,MCO,615369105,"7,799,843","24,669,778",2.48
14,DAVITA INC,DVA,23918K108,"3,412,114","36,095,570",1.08
18,HP INC,HPQ,40434L105,"2,634,739","102,519,035",0.84
44,VERISIGN INC,VRSN,92343E102,"2,595,546","12,815,613",0.82
11,CITIGROUP INC,C,172967424,"2,272,218","55,244,797",0.72
21,KROGER CO,KR,501044101,"2,237,500","50,000,000",0.71
45,VISA INC,V,92826C839,"1,908,498","8,297,460",0.61
10,CHUBB LIMITED,CB,H1467J104,"1,695,320","8,143,530",0.54
8,CHARTER COMMUNICATIONS INC N,CHTR,16119P108,"1,684,044","3,828,941",0.53
32,MASTERCARD INC,MA,57636Q104,"1,578,353","3,986,648",0.50
3,AON PLC,AON,G0403H108,"1,329,302","4,100,000",0.42
1,AMAZON COM INC,AMZN,023135106,"1,271,200","10,000,000",0.40
7,CAPITAL ONE FINL CORP,COF,14040H105,"1,210,313","12,471,030",0.38
37,PARAMOUNT GLOBAL,PARA,92556H206,"1,209,129","93,730,975",0.38
27,LIBERTY MEDIA CORP DEL,LSXMK,531229789,"1,100,083","43,208,291",0.35
39,SNOWFLAKE INC,SNOW,833445109,"935,773","6,125,376",0.30
34,NU HLDGS LTD,NU,G6683N103,"776,611","107,118,784",0.25
0,ALLY FINL INC,ALLY,02005N100,"773,720","29,000,000",0.25
42,T-MOBILE US INC,TMUS,872590104,"734,142","5,242,000",0.23
13,D R HORTON INC,DHI,23331A109,"641,565","5,969,714",0.20
28,LIBERTY MEDIA CORP DEL,LSXMA,531229813,"514,285","20,207,680",0.16
29,LIBERTY MEDIA CORP DEL,531229854,531229854,"481,108","7,722,451",0.15
16,FLOOR & DECOR HLDGS INC,FND,339750101,"432,590","4,780,000",0.14
30,LOUISIANA PAC CORP,LPX,546347105,"389,372","7,044,909",0.12
25,LIBERTY MEDIA CORP DEL,LLYVK,531229722,"357,356","11,132,590",0.11
31,MARKEL CORP,MKL,570535104,"233,706","158,715",0.07
26,LIBERTY MEDIA CORP DEL,LLYVA,531229748,"161,257","5,051,918",0.05
41,STONECO LTD,STNE,G85158106,"114,120","10,695,448",0.04
17,GLOBE LIFE INC,GL,37959E102,"90,356","831,014",0.03
35,NVR INC,NVR,62944T105,"66,264","11,112",0.02
38,SIRIUS XM HOLDINGS INC,SIRI,82968B103,"43,768","9,683,224",0.01
15,DIAGEO P L C,DEO,25243Q205,"33,975","227,750",0.01
23,LIBERTY LATIN AMERICA LTD,LILA,G9001E102,"21,467","2,630,792",0.01
43,VANGUARD INDEX FDS,VOO,922908363,"16,886","43,000",0.01
40,SPDR S&P 500 ETF TR,SPY,78462F103,"16,842","39,400",0.01
19,JEFFERIES FINL GROUP INC,JEF,47233W109,"15,881","433,558",0.01
22,LENNAR CORP,LEN.B,526057302,"15,597","152,572",0.00
24,LIBERTY LATIN AMERICA LTD,LILAK,G9001E128,"10,477","1,284,020",0.00
5,ATLANTA BRAVES HLDGS INC,BATRK,047726302,"7,990","223,645",0.00

In [4]:
#
# Get reports for the last years
#
import report_collection as qrc
reports_collection = qrc.QuarterlyReportsCollection("0001067983", 2023, 2024)
reports_collection.display_reports("value")

,Name,Symbol,2023-Q1,2023-Q2,2023-Q3,2023-Q4,2024-Q1,2024-Q2
5,APPLE INC,AAPL,150975907,177591247,156753093,174347467,135360902,84248000
7,BANK AMER CORP,BAC,29539567,29632524,28279488,34776127,39165748,41076524
3,AMERICAN EXPRESS CO,AXP,25008185,26410584,22618800,28402749,34520240,35105458
14,COCA COLA CO,KO,24812000,24088000,22392000,23572000,24472000,25460000
11,CHEVRON CORP NEW,CVX,21603623,19372951,18590066,18808081,19398898,18553060
46,OCCIDENTAL PETE CORP,OXY,13216875,13178796,14541502,14552271,16118698,16090394
25,KRAFT HEINZ CO,KHC,12592298,11560036,10954355,12041976,12015925,10491954
43,MOODYS CORP,MCO,7549445,8578175,7799844,9635028,9695963,10384250
0,ACTIVISION BLIZZARD INC,00507V109,4231551,1235680,0,0,0,0
22,HP INC,HPQ,3549965,3714461,2634739,687638,0,0
16,DAVITA INC,DVA,2927712,3626522,3412114,3781372,4982993,5001763
57,VERISIGN INC,VRSN,2708323,2895944,2595546,2639504,2428687,2278616
13,CITIGROUP INC,C,2590429,2543470,2272219,2841792,3493681,3505835
26,KROGER CO,KR,2468500,2350000,2237500,2285500,2856500,2496500
47,PARAMOUNT GLOBAL,PARA,2091138,1491260,1209130,936540,88649,0
58,VISA INC,V,1870745,1970481,1908499,2160244,2315655,2177834
19,GENERAL MTRS CO,GM,1467200,848320,0,0,0,0
40,MASTERCARD INC,MA,1448788,1567949,1578354,1700345,1919850,1758750
10,CHARTER COMMUNICATIONS INC N,CHTR,1369268,1406638,1684045,1488233,1112805,1144700
4,AON PLC,AON,1366782,1496442,1329302,1193182,1368252,1203678
36,LIBERTY MEDIA CORP DELAWARE,531229607,1209400,1414207,0,0,0,0
2,AMAZON COM INC,AMZN,1089813,1375428,1271200,1519400,1803800,1932500
9,CELANESE CORP DEL,CE,960303,620518,0,0,0,0
8,CAPITAL ONE FINL CORP,COF,954100,1363957,1210313,1635201,1856812,1359448
50,SNOWFLAKE INC,SNOW,945084,1077944,935774,1218950,989861,0
41,MCKESSON CORP,MCK,815306,0,0,0,0,0
53,T-MOBILE US INC,TMUS,759251,728114,734142,840450,855599,823113
1,ALLY FINL INC,ALLY,739210,783290,773720,1012680,1177110,1150430
20,GLOBE LIFE INC,GL,699037,275757,90356,0,0,0
38,MARKEL CORP,MKL,602504,652392,233706,0,0,0
30,LIBERTY MEDIA CORP DEL,531229854,577871,581346,481109,487518,506593,554781
35,LIBERTY MEDIA CORP DELAWARE,531229409,567634,663014,0,0,0,0
44,NU HLDGS LTD,NU,509885,845167,776611,892299,1277927,1380761
18,FLOOR & DECOR HLDGS INC,FND,469492,496929,432590,533257,619584,395440
37,LOUISIANA PAC CORP,LPX,381905,528227,389372,498991,553634,491081
52,STONECO LTD,STNE,102035,136260,114120,0,0,0
39,MARSH & MCLENNAN COS INC,MMC,67438,0,0,0,0,0
24,JOHNSON & JOHNSON,JNJ,50700,54142,0,0,0,0
48,PROCTER & GAMBLE CO,PG,46897,47859,0,0,0,0
17,DIAGEO P L C,DEO,41264,39510,33976,33174,33876,28715
42,MONDELEZ INTL INC,MDLZ,40298,42159,0,0,0,0
28,LIBERTY LATIN AMERICA LTD,LILA,21862,23019,21467,19231,18337,25282
56,VANGUARD INDEX FDS,VOO,16171,17513,16886,18782,20670,21506
51,SPDR S&P 500 ETF TR,SPY,16130,17465,16843,18727,20609,21442
23,JEFFERIES FINL GROUP INC,JEF,13761,14381,15881,17520,19120,21574
55,UNITED PARCEL SERVICE INC,UPS,11523,10647,0,0,0,0
29,LIBERTY LATIN AMERICA LTD,LILAK,10606,11068,10478,9425,8975,12352
59,VITESSE ENERGY INC,VTS,971,0,0,0,0,0
54,ULTA BEAUTY INC,ULTA,0,0,0,0,0,266291
12,CHUBB LIMITED,CB,0,0,1695320,4542600,6717645,6895778
15,D R HORTON INC,DHI,0,726454,641565,0,0,0
6,ATLANTA BRAVES HLDGS INC,BATRK,0,0,7991,8852,8736,8821
31,LIBERTY MEDIA CORP DEL,LLYVA,0,0,161257,184648,213949,187047
49,SIRIUS XM HOLDINGS INC,SIRI,0,0,43768,220130,142326,376045
21,HEICO CORP NEW,HEI.A,0,0,0,0,0,185374
32,LIBERTY MEDIA CORP DEL,LLYVK,0,0,357356,416248,487830,417819
27,LENNAR CORP,LEN.B,0,17238,15597,20452,23524,21273
34,LIBERTY MEDIA CORP DEL,LSXMK,0,0,1100083,1243535,1945598,1551264
33,LIBERTY MEDIA CORP DEL,LSXMA,0,0,514285,580769,972842,779286
45,NVR INC,NVR,0,70568,66264,77789,90007,84324

In [5]:
# show distribution by fraction of total value
reports_collection.display_reports("fraction")

,Name,Symbol,2023-Q1,2023-Q2,2023-Q3,2023-Q4,2024-Q1,2024-Q2
5,APPLE INC,AAPL,7.74,9.10,8.03,8.93,6.94,4.32
7,BANK AMER CORP,BAC,1.51,1.52,1.45,1.78,2.01,2.10
3,AMERICAN EXPRESS CO,AXP,1.28,1.35,1.16,1.46,1.77,1.80
14,COCA COLA CO,KO,1.27,1.23,1.15,1.21,1.25,1.30
11,CHEVRON CORP NEW,CVX,1.11,0.99,0.95,0.96,0.99,0.95
46,OCCIDENTAL PETE CORP,OXY,0.68,0.68,0.75,0.75,0.83,0.82
25,KRAFT HEINZ CO,KHC,0.65,0.59,0.56,0.62,0.62,0.54
43,MOODYS CORP,MCO,0.39,0.44,0.40,0.49,0.50,0.53
0,ACTIVISION BLIZZARD INC,00507V109,0.22,0.06,0.00,0.00,0.00,0.00
22,HP INC,HPQ,0.18,0.19,0.13,0.04,0.00,0.00
16,DAVITA INC,DVA,0.15,0.19,0.17,0.19,0.26,0.26
57,VERISIGN INC,VRSN,0.14,0.15,0.13,0.14,0.12,0.12
13,CITIGROUP INC,C,0.13,0.13,0.12,0.15,0.18,0.18
26,KROGER CO,KR,0.13,0.12,0.11,0.12,0.15,0.13
47,PARAMOUNT GLOBAL,PARA,0.11,0.08,0.06,0.05,0.00,0.00
58,VISA INC,V,0.10,0.10,0.10,0.11,0.12,0.11
19,GENERAL MTRS CO,GM,0.08,0.04,0.00,0.00,0.00,0.00
10,CHARTER COMMUNICATIONS INC N,CHTR,0.07,0.07,0.09,0.08,0.06,0.06
40,MASTERCARD INC,MA,0.07,0.08,0.08,0.09,0.10,0.09
4,AON PLC,AON,0.07,0.08,0.07,0.06,0.07,0.06
2,AMAZON COM INC,AMZN,0.06,0.07,0.07,0.08,0.09,0.10
36,LIBERTY MEDIA CORP DELAWARE,531229607,0.06,0.07,0.00,0.00,0.00,0.00
50,SNOWFLAKE INC,SNOW,0.05,0.06,0.05,0.06,0.05,0.00
9,CELANESE CORP DEL,CE,0.05,0.03,0.00,0.00,0.00,0.00
8,CAPITAL ONE FINL CORP,COF,0.05,0.07,0.06,0.08,0.10,0.07
20,GLOBE LIFE INC,GL,0.04,0.01,0.00,0.00,0.00,0.00
53,T-MOBILE US INC,TMUS,0.04,0.04,0.04,0.04,0.04,0.04
41,MCKESSON CORP,MCK,0.04,0.00,0.00,0.00,0.00,0.00
1,ALLY FINL INC,ALLY,0.04,0.04,0.04,0.05,0.06,0.06
44,NU HLDGS LTD,NU,0.03,0.04,0.04,0.05,0.07,0.07
35,LIBERTY MEDIA CORP DELAWARE,531229409,0.03,0.03,0.00,0.00,0.00,0.00
38,MARKEL CORP,MKL,0.03,0.03,0.01,0.00,0.00,0.00
30,LIBERTY MEDIA CORP DEL,531229854,0.03,0.03,0.02,0.02,0.03,0.03
18,FLOOR & DECOR HLDGS INC,FND,0.02,0.03,0.02,0.03,0.03,0.02
37,LOUISIANA PAC CORP,LPX,0.02,0.03,0.02,0.03,0.03,0.03
52,STONECO LTD,STNE,0.01,0.01,0.01,0.00,0.00,0.00
33,LIBERTY MEDIA CORP DEL,LSXMA,0.00,0.00,0.03,0.03,0.05,0.04
6,ATLANTA BRAVES HLDGS INC,BATRK,0.00,0.00,0.00,0.00,0.00,0.00
12,CHUBB LIMITED,CB,0.00,0.00,0.09,0.23,0.34,0.35
56,VANGUARD INDEX FDS,VOO,0.00,0.00,0.00,0.00,0.00,0.00
55,UNITED PARCEL SERVICE INC,UPS,0.00,0.00,0.00,0.00,0.00,0.00
54,ULTA BEAUTY INC,ULTA,0.00,0.00,0.00,0.00,0.00,0.01
15,D R HORTON INC,DHI,0.00,0.04,0.03,0.00,0.00,0.00
51,SPDR S&P 500 ETF TR,SPY,0.00,0.00,0.00,0.00,0.00,0.00
17,DIAGEO P L C,DEO,0.00,0.00,0.00,0.00,0.00,0.00
49,SIRIUS XM HOLDINGS INC,SIRI,0.00,0.00,0.00,0.01,0.01,0.02
48,PROCTER & GAMBLE CO,PG,0.00,0.00,0.00,0.00,0.00,0.00
21,HEICO CORP NEW,HEI.A,0.00,0.00,0.00,0.00,0.00,0.01
34,LIBERTY MEDIA CORP DEL,LSXMK,0.00,0.00,0.06,0.06,0.10,0.08
45,NVR INC,NVR,0.00,0.00,0.00,0.00,0.00,0.00
23,JEFFERIES FINL GROUP INC,JEF,0.00,0.00,0.00,0.00,0.00,0.00
24,JOHNSON & JOHNSON,JNJ,0.00,0.00,0.00,0.00,0.00,0.00
42,MONDELEZ INTL INC,MDLZ,0.00,0.00,0.00,0.00,0.00,0.00
27,LENNAR CORP,LEN.B,0.00,0.00,0.00,0.00,0.00,0.00
28,LIBERTY LATIN AMERICA LTD,LILA,0.00,0.00,0.00,0.00,0.00,0.00
39,MARSH & MCLENNAN COS INC,MMC,0.00,0.00,0.00,0.00,0.00,0.00
29,LIBERTY LATIN AMERICA LTD,LILAK,0.00,0.00,0.00,0.00,0.00,0.00
31,LIBERTY MEDIA CORP DEL,LLYVA,0.00,0.00,0.01,0.01,0.01,0.01
32,LIBERTY MEDIA CORP DEL,LLYVK,0.00,0.00,0.02,0.02,0.02,0.02
59,VITESSE ENERGY INC,VTS,0.00,0.00,0.00,0.00,0.00,0.00